build sdk package for the installer

diff --git a/files/setup-sdk.sh.in b/files/setup-sdk.sh.in
--- a/files/setup-sdk.sh.in
+++ b/files/setup-sdk.sh.in
@@ -1,108 +1,175 @@
-#! /bin/bash
+#!/bin/sh
 
-if [ $# -gt 0 ]; then
-    echo "Usage: $0"
-    echo "  Setup the SDK to be use at this location."
-    if [ "$1" == "-h" -o "$1" == "--help" ]; then
-        exit 0
-    else
+INST_ARCH=$(uname -m | sed -e "s/i[3-6]86/ix86/" -e "s/x86[-_]64/x86_64/")
+SDK_ARCH=$(echo @SDK_ARCH@ | sed -e "s/i[3-6]86/ix86/" -e "s/x86[-_]64/x86_64/")
+
+verlte () {
+	[  "$1" = "`printf "$1\n$2" | sort -V | head -n1`" ]
+}
+
+verlt() {
+	[ "$1" = "$2" ] && return 1 || verlte $1 $2
+}
+
+verlt `uname -r` @OLDEST_KERNEL@
+if [ $? = 0 ]; then
+	echo "Error: The SDK needs a kernel > @OLDEST_KERNEL@"
 	exit 1
-    fi
 fi
 
-SDK_TARGET_DIRECTORY="$(cd $(dirname $(readlink -f $0)) && pwd)"
-SDK_DEFAULT_TARGET_DIRECTORY="$(cat ${SDK_TARGET_DIRECTORY}/last-install-directory)"
-SDK_ENV_SETUP_SCRIPT="${SDK_TARGET_DIRECTORY}/environment-setup-@REAL_MULTIMACH_TARGET_SYS@"
-REPLACES="s:${SDK_DEFAULT_TARGET_DIRECTORY}:${SDK_TARGET_DIRECTORY}:g"
+if [ "$INST_ARCH" != "$SDK_ARCH" ]; then
+	# Allow for installation of ix86 SDK on x86_64 host
+	if [ "$INST_ARCH" != x86_64 -o "$SDK_ARCH" != ix86 ]; then
+		echo "Error: Installation machine not supported!"
+		exit 1
+	fi
+fi
 
+DEFAULT_INSTALL_DIR="@SDKPATH@"
+SUDO_EXEC=""
+target_sdk_dir="$(cd $(dirname $(readlink -f $0)) && pwd)"
+answer=""
+relocate=1
+savescripts=0
+verbose=0
+while getopts ":yd:nDRS" OPT; do
+	case $OPT in
+	y)
+		answer="Y"
+		;;
+	d)
+		target_sdk_dir=$OPTARG
+		;;
+	n)
+		prepare_buildsystem="no"
+		;;
+	D)
+		verbose=1
+		;;
+	R)
+		relocate=0
+		savescripts=1
+		;;
+	S)
+		savescripts=1
+		;;
+	*)
+		echo "Usage: $(basename $0) [-y] [-d <dir>]"
+		echo "  -y         Automatic yes to all prompts"
+		echo "  -d <dir>   Install the SDK to <dir>"
+		echo "======== Extensible SDK only options ============"
+		echo "  -n         Do not prepare the build system"
+		echo "======== Advanced DEBUGGING ONLY OPTIONS ========"
+		echo "  -S         Save relocation scripts"
+		echo "  -R         Do not relocate executables"
+		echo "  -D         use set -x to see what is going on"
+		exit 1
+		;;
+	esac
+done
+
+titlestr="@SDK_TITLE@ installer version @SDK_VERSION@"
+printf "%s\n" "$titlestr"
+printf "%${#titlestr}s\n" | tr " " "="
+
+if [ $verbose = 1 ] ; then
+	set -x
+fi
+
+@SDK_PRE_INSTALL_COMMAND@
+
+# SDK_EXTENSIBLE is exposed from the SDK_PRE_INSTALL_COMMAND above
+if [ "$SDK_EXTENSIBLE" = "1" ]; then
+	DEFAULT_INSTALL_DIR="@SDKEXTPATH@"
+fi
+
+if [ "$target_sdk_dir" = "" ]; then
+	if [ "$answer" = "Y" ]; then
+		target_sdk_dir="$DEFAULT_INSTALL_DIR"
+	else
+		read -p "Enter target directory for SDK (default: $DEFAULT_INSTALL_DIR): " target_sdk_dir
+		[ "$target_sdk_dir" = "" ] && target_sdk_dir=$DEFAULT_INSTALL_DIR
+	fi
+fi
+
+eval target_sdk_dir=$(echo "$target_sdk_dir"|sed 's/ /\\ /g')
+if [ -d "$target_sdk_dir" ]; then
+	target_sdk_dir=$(cd "$target_sdk_dir"; pwd)
+else
+	target_sdk_dir=$(readlink -m "$target_sdk_dir")
+fi
+
+if [ "$SDK_EXTENSIBLE" = "1" ]; then
+	# We're going to be running the build system, additional restrictions apply
+	if echo "$target_sdk_dir" | grep -q '[+\ @$]'; then
+		echo "The target directory path ($target_sdk_dir) contains illegal" \
+		     "characters such as spaces, @, \$ or +. Abort!"
+		exit 1
+	fi
+else
+	if [ -n "$(echo $target_sdk_dir|grep ' ')" ]; then
+		echo "The target directory path ($target_sdk_dir) contains spaces. Abort!"
+		exit 1
+	fi
+fi
+
+if [ ! -e "$target_sdk_dir/environment-setup-@REAL_MULTIMACH_TARGET_SYS@" ]; then
+	echo "The directory \"$target_sdk_dir\" does not contains a SDK for this architecture."
+	echo "Installation aborted!"
+	exit 1
+fi
+
+# if don't have the right to access dir, gain by sudo 
+if [ ! -x $target_sdk_dir -o ! -w $target_sdk_dir -o ! -r $target_sdk_dir ]; then 
+	if [ "$SDK_EXTENSIBLE" = "1" ]; then
+		echo "Unable to access \"$target_sdk_dir\", will not attempt to use" \
+		     "sudo as as extensible SDK cannot be used as root."
+		exit 1
+	fi
+
+	SUDO_EXEC=$(which "sudo")
+	if [ -z $SUDO_EXEC ]; then
+		echo "No command 'sudo' found, please install sudo first. Abort!"
+		exit 1
+	fi
+
+	# test sudo could gain root right
+	$SUDO_EXEC pwd >/dev/null 2>&1
+	[ $? -ne 0 ] && echo "Sorry, you are not allowed to execute as root." && exit 1
+
+fi
+
+printf "Setting it up..."
 # fix environment paths
-sed -e ${REPLACES} -i ${SDK_ENV_SETUP_SCRIPT}
-
-# fix dynamic loader paths in all ELF SDK binaries
-NATIVE_SYSROOT=$(cat ${SDK_ENV_SETUP_SCRIPT} \
-                 | grep 'OECORE_NATIVE_SYSROOT=' \
-                 | cut -d'=' -f2 \
-                 | tr -d '"')
-DL_PATH=$(find ${NATIVE_SYSROOT}/lib -name "ld-linux*")
-if [ "$DL_PATH" = "" ] ; then
-    echo "error: relocate script unable to find ld-linux.so"
-    exit 1
-fi
-EXECUTABLE_FILES=$(find ${NATIVE_SYSROOT} -type f -perm /111 -exec file '{}' \; \
-                   | grep "\(executable\|dynamically linked\)" \
-                   | cut -f 1 -d ':')
-${SDK_TARGET_DIRECTORY}/relocate_sdk.py \
-    ${SDK_TARGET_DIRECTORY} ${DL_PATH} ${EXECUTABLE_FILES}
-if [ $? -ne 0 ]; then
-    echo "error: relocate script failed"
-    exit 1
+real_env_setup_script=""
+for env_setup_script in `ls $target_sdk_dir/environment-setup-*`; do
+	if grep -q 'OECORE_NATIVE_SYSROOT=' $env_setup_script; then
+		# Handle custom env setup scripts that are only named
+		# environment-setup-* so that they have relocation
+		# applied - what we want beyond here is the main one
+		# rather than the one that simply sorts last
+		real_env_setup_script="$env_setup_script"
+	fi
+	$SUDO_EXEC sed -e "s:@SDKPATH@:$target_sdk_dir:g" -i $env_setup_script
+done
+if [ -n "$real_env_setup_script" ] ; then
+	env_setup_script="$real_env_setup_script"
 fi
 
-# fix all text files: configs/scripts/etc
-find ${NATIVE_SYSROOT} -type f -exec file '{}' \; \
-| grep ":.*\(ASCII\|script\|source\).*text" \
-| cut -d':' -f1 \
-| xargs sed -i -e ${REPLACES}
+@SDK_POST_INSTALL_COMMAND@
 
-# fix all symlinks
-for l in $(find ${NATIVE_SYSROOT} -type l); do
-    ln -sfn $(readlink $l | sed -e ${REPLACES}) $l
-done
-
-# find out all perl scripts in ${NATIVE_SYSROOT} and modify them replacing the
-# host perl with SDK perl
-for perl_script in $(grep "^#!.*perl" -rl ${NATIVE_SYSROOT}); do
-    sed -i -e "s:^#! */usr/bin/perl.*:#! /usr/bin/env perl:g" \
-           -e "s: /usr/bin/perl: /usr/bin/env perl:g" $perl_script
-done
-
-source ${SDK_ENV_SETUP_SCRIPT}
-
-# We need to create a new mkspec for the installed SDK without environment
-# variables
-
-# Set OE_QMAKE_COMPILER as environment-setup-@REAL_MULTIMACH_TARGET_SYS@ does
-# not set it
-OE_QMAKE_COMPILER=gcc
-
-MKSPEC="linux-@DISTRO@-g++"
-MKSPEC_PATH="$QMAKESPEC/../$MKSPEC"
-cp -r "$QMAKESPEC" "$MKSPEC_PATH"
-error_code=$?
-if [ $error_code -ne 0 ]; then
-    echo "error: copy of OE mkspec failed"
-    exit $error_code
+# delete the relocating script, so that user is forced to re-run the installer
+# if he/she wants another location for the sdk
+if [ $savescripts = 0 ] ; then
+	$SUDO_EXEC rm -f ${env_setup_script%/*}/relocate_sdk.py ${env_setup_script%/*}/relocate_sdk.sh
 fi
 
-VARLIST=$(sed -n 's/.*$(\(.*\)).*/\1/p' "$MKSPEC_PATH/qmake.conf" | sort -u)
-REPLACES=
-
-for VAR in $VARLIST; do
-    EVAL=${!VAR}
-    REPLACES+="s@\$($VAR)@$EVAL@g; "
+echo "SDK has been successfully set up and is ready to be used."
+echo "Each time you wish to use the SDK in a new shell session, you need to source the environment setup script e.g."
+for env_setup_script in `ls $target_sdk_dir/environment-setup-*`; do
+	echo " \$ . $env_setup_script"
 done
-
-sed -i "$REPLACES" "$MKSPEC_PATH/qmake.conf"
-
-# set absolute paths
-VARLIST=" \
-QMAKE_AR \
-QMAKE_STRIP \
-QMAKE_WAYLAND_SCANNER \
-QMAKE_CC \
-QMAKE_CXX \
-QMAKE_LINK \
-QMAKE_LINK_SHLIB \
-QMAKE_LINK_C \
-QMAKE_LINK_C_SHLIB \
-"
-
-for VAR in $VARLIST; do
-    VALUE=$(sed -n "s/$VAR *= *\([^ ]*\).*/\1/p" "$MKSPEC_PATH/qmake.conf")
-    ABSOLUTE_VALUE=$(command -v $VALUE)
-    sed -i "s%\($VAR *= *\)$VALUE%\1$ABSOLUTE_VALUE%" "$MKSPEC_PATH/qmake.conf"
-done
-
-echo "${SDK_TARGET_DIRECTORY}" > ${SDK_TARGET_DIRECTORY}/last-install-directory
 
 exit 0
+
+MARKER:
